swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /predictCancellazioni:
    post:
      operationId: "ml_cancellazioni.predict"
      tags:
        - "Cancellazioni"
      summary: "Previsione Cancellazione"
      description: "Data una prenotazione, restituisce la previsione sulla cancellazione ed il grado di certezza"
      parameters:
        - name: prenotazione
          in: body
          description: La prenotazione
          required: True
          schema:
            type: object
            properties:
              PrenotazioneHotel:
                type: string
                description: L'Hotel prenotato
              DataPrenotazioneArrivo:
                type: string
                description: La data di Arrivo prevista
              DataPrenotazionePartenza:
                type: string
                description: La data di Partenza prevista
              PrenotazioneAdulti:
                type: number
                description: Quanti Adulti
              PrenotazioneBambini:
                type: number
                description: Quanti bambini
              PrenotazioneInfant:
                type: number
                description: Quanti neonati
              PrenotazioneCamera:
                type: string
                description: Tipologia di camera prenotata
              PrenotazioneSpeciali:
                type: number
                description: Quante richieste speciali
              PrenotazioneTrattamento:
                type: string
                description: Trattamento
              PrenotazionePostiAuto:
                type: number
                description: Quanti Posti Auto
      responses:
        200:
          description: "La previsione"
          schema:
            type: "object"
            properties:
              previsione:
                type: "boolean"
              certezza:
                type: "number"
